par(mar=c(4, 4, 4, 4), oma=c(4, 0, 0, 0))
plot(rnorm(20), pch=16, col="blue", type="o", xlab="", ylab="")
title(main="Main title on line1", line=1)
title(main="Main title on line2", line=2)
title(main="Main title on line3", line=3)
title(sub="subtitle on line1", line=1, outer=T)
title(sub=" subtitle on line2", line=2, outer=T)
title(sub=" subtitle on line3", line=3, outer=T)
title(xlab="X lable on line1", line=1)
title(xlab="X lable on line2", line=2)
title(xlab="X lable on line3", line=3)
title(ylab="Y lable on line1", line=1)
title(ylab="Y lable on line2", line=2)
