plot(1:10, type="n", xlab="", ylab="", main="legend")
legend("bottomright", "(x, y)", pch=1, title="bottomright")
legend("bottom", "(x, y)", pch=1, title="bottom")
legend("bottomleft", "(x, y)", pch=1, title="bottomleft")
legend("left", "(x, y)", pch=1, title="left")
legend("topleft", "(x, y)", pch=1, title="topleft")
legend("top", "(x, y)", pch=1, title="top")
legend("topright", "(x, y)", pch=1, title="topright")
legend("right", "(x, y)", pch=1, title="right")
legend("center", "(x, y)", pch=1, title="center")
legends <- c("Legend1", "Legend2")
legend(3, 8, legend=legends, pch=1:2, col=1:2)
legend(7, 8, legend=legends, pch=1:2, col=1:2, lty=1:2)
legend(3, 4, legend=legends, fill=1:2)
legend(7, 4, legend=legends, fill=1:2, density=30)
legend(locator(1), legend="Locator", fill=1)
